module.exports = [{
  // english 
  // header部分
  home: 'Home',
  account: 'Account',
  contact: 'Contact',
  language: 'Chinese<img class="flag" src="/static/imgs/chn.png">',
  submit: 'submit',
  login_tip: 'login to check you data',
  login_ph: 'pleace enter your s-id',
  // home
  home_title_1: 'How to',
  home_title_2: 'monetize<br>your sports data?',
  home_tip: 'send your E-mail to acquire bonus',
  home_ph: 'please enter your e-mail',

  section1_top: 'Our mission is maximize the Sports Data value engage with Entertainment, collaborate each individual through crypto blockchain technology, how can we make it happen',
  section1_m_1t: 'Creat A SB',
  section1_m_1p: 'Sign up for free, <br>bond to Wechat,<br>synchronize run data everyday',
  section1_m_2t: 'Synchronization',
  section1_m_2p: 'Get converted coin <br>when you run sport data, <br>activity reward as well',
  section1_m_3t: 'Get Reward',
  section1_m_3p: 'Log in and<br>pick up your award',

  section3_t_1: 'Basic',
  section3_t_2: 'Medium',
  section3_t_3: 'Premium',
  section3_t_4: 'Supreme',

  section3_basic_1: 'DJI Osmo Action Cam Digital Camera with 2 displays 11m waterproof 4K HDR-Video 12MP 145° Angle Black<br>Osmo Action helps you record the passage of time more easily than ever. Just mark where you want the camera movement to start and end. and tap ‘start’ to create phenomenal moving timelapses without additional specialist equipment.',
  section3_basic_2: 'AutoCare Formaldehyde Romover. <br>Visible High-efficiency formaldehyde VOC measurement & absorption, serial applicated in OEM Audi、Ford、BMW、GM models, fully body-harmless . Suitable for New vehicle air quality improvement , in-house air testing and VOC removal. AutoCare oriented from Nanjing University Lab , dedicate to help families having safety air, green life.',
  section3_medium_1: 'DJI Osmo Action Cam Digital Camera with 2 displays 11m waterproof 4K HDR-Video 12MP 145° Angle Black<br>Osmo Action helps you record the passage of time more easily than ever. Just mark where you want the camera movement to start and end. and tap ‘start’ to create phenomenal moving timelapses without additional specialist equipment.',
  section3_medium_2: 'AutoCare Formaldehyde Romover. <br>Visible High-efficiency formaldehyde VOC measurement & absorption, serial applicated in OEM Audi、Ford、BMW、GM models, fully body-harmless . Suitable for New vehicle air quality improvement , in-house air testing and VOC removal. AutoCare oriented from Nanjing University Lab , dedicate to help families having safety air, green life.',
  section3_premium_1: 'DJI Osmo Action Cam Digital Camera with 2 displays 11m waterproof 4K HDR-Video 12MP 145° Angle Black<br>Osmo Action helps you record the passage of time more easily than ever. Just mark where you want the camera movement to start and end. and tap ‘start’ to create phenomenal moving timelapses without additional specialist equipment.',
  section3_premium_2: 'AutoCare Formaldehyde Romover. <br>Visible High-efficiency formaldehyde VOC measurement & absorption, serial applicated in OEM Audi、Ford、BMW、GM models, fully body-harmless . Suitable for New vehicle air quality improvement , in-house air testing and VOC removal. AutoCare oriented from Nanjing University Lab , dedicate to help families having safety air, green life.',
  section3_superme_1: 'DJI Osmo Action Cam Digital Camera with 2 displays 11m waterproof 4K HDR-Video 12MP 145° Angle Black<br>Osmo Action helps you record the passage of time more easily than ever. Just mark where you want the camera movement to start and end. and tap ‘start’ to create phenomenal moving timelapses without additional specialist equipment.',
  section3_superme_2: 'AutoCare Formaldehyde Romover. <br>Visible High-efficiency formaldehyde VOC measurement & absorption, serial applicated in OEM Audi、Ford、BMW、GM models, fully body-harmless . Suitable for New vehicle air quality improvement , in-house air testing and VOC removal. AutoCare oriented from Nanjing University Lab , dedicate to help families having safety air, green life.',

  section4_t: 'Balance Distribution & Reward Mechanism',
  section4_m_p: 'The Stepbook tokens are a key element which facilitate all interaction in the system in relation to the entertainment and a healthy lifestyle. The tokens are used to incentivize people to be active participants, make connections and improve their health. The tokens will distribute on the next generation cryptocurrency blockchain. This, of course, imposes certain standard rules for the community.',
  section4_m_btn: 'Formula Details',
  section4_p_1: 'Persistent',
  section4_p_2: 'Steps',
  section4_p_3: 'Invitation',
  section4_p_4: 'Subscription',
  section4_p_5: 'Game',
  section4_p_6: 'Contribution',
  section4_p_7: 'Popularity',

  section5_step: 'Step',
  section5_pet_t: 'Crypto Pet have the unique gene, stepbook allow our runner own their own blockchain tech based pets, as well your dog in real world, accompany with you, have fun, pet social, participant in game and rewarding. Furthermore, crypto pet will never die.',
  section5_pet_1: 'Austrlia Rabbit',
  section5_pet_2: 'Smile Frog',
  section5_pet_3: 'Crazy Penguin',

  section6_t: 'Blockchain based crypto pet is another "U" in parallel scion',
  section6_p1_1: 'Entertainment',
  section6_p1_2: 'Game',
  section6_p1_3: 'Like pet will have intelligence assist master to finish some award paid games.',
  section6_p2_1: 'Diversity',
  section6_p2_2: 'Uniqueness',
  section6_p2_3: 'Over 10 race graphic designs, varieties keep ramp up each pet have unique digital DNA, they feed by different kinds of data, they are valued link to data itself.',
  section6_p3_1: 'Hierarchy',
  section6_p3_2: 'Merit',
  section6_p3_3: 'Grown via dada bond, normally high quality ingredient make better perform to step over.',

  section7_t: 'Stepbook applet make the first ground blockchain project, Easy driven by only WeChat data, superior level which need support multi-dimensionality should live in wearable devices.',
  section7_1_t: 'Quick Move',
  section7_1_p: 'Whether it\'s IOS nor Android OS, sporter just need to register from WeChat profile, we allow data flowing to stepbook pool automatically.',
  section7_2_t: 'Convert',
  section7_2_p: 'Initiative sport undertake consistency testing, core mechanism to help verify security. Push Convert Button ,then you can get your deserved asset.',
  section7_3_t: 'Sponsors',
  section7_3_p: 'You can choose each sponsors you want, all is from partner, you coins will be write off after you finish exchange. That is mean, total coin volume will cut down perpetually.',
  section7_4_t: 'Subscribe Us',

  section8_1_t: 'Jun.2019',
  section8_1_p: 'stepbook.io Launch + First Roadshow<br>Bracelet data-miner + Fisrt User Conference',
  section8_2_t: 'Oct.2019',
  section8_2_p: 'app Launch +app Roadshow <br>Crypto pet arrival + First online running event',
  section8_3_t: 'Mar.2020',
  section8_3_p: 'Social run-map +100,000 users<br>First Ads Model +offline running event',
  section8_4_t: 'Apr.2020',
  section8_4_p: 'Blockchain Integration + A big commerce partner',
  section8_5_t: 'Sep.2020',
  section8_5_p: 'stepbook team expansion to >20 + ZB.com exchange ICO<br>Beta version of running event + Regional running competition league', 
  
  account_balance: 'Balance',
  account_b1: 'Accumulated Days',
  account_b2: 'Promotion Visitors',
  account_b3: 'Stage Clear Bonus',
  account_b4: 'Contribution Bonus',

  section9_p_1: 'Something incrediable is waiting to be known',
  section9_p_2: 'Our Sponsors',
  section9_p_3: 'Our Customers',
  section9_p_4: 'Someone want to join us ',
  section9_l_1: 'Name',
  section9_l_2: 'Email',
  section9_l_3: 'City',
  section9_l_4: 'Message',
  section9_l_5: 'SEND',
}, {
  // 中文
  // header部分
  home: '主页',
  account: '账户',
  contact: '联系我们',
  language: 'EN<img class="flag" src="/static/imgs/eng.png">',
  submit: '提交',
  login_tip: '登录查看你的钱包',
  login_ph: '请输入你的ID',
  // home
  home_title_1: '加入',
  home_title_2: 'stepbook.io<br>挖掘每一滴汗水的数据价值',

  home_tip: '输入邮箱订阅，得到最新消息以及额外奖励',
  home_ph: '请输入你的邮箱',

  section1_top: 'stepbook致力于实现运动数据的货币化，数据结构的区块链化，运动方式的娱乐化。数据创造的价值重新归属运动者本身，不再被机构偷走。实现它只要三步。',
  section1_m_1t: '账号创建',
  section1_m_1p: '免费注册账号<br>绑定微信<br>',
  section1_m_2t: '数据同步',
  section1_m_2p: '坚持更新运动数据<br>并转换成stepbook奖励积分<br>',
  section1_m_3t: '数据变现',
  section1_m_3p: '直接兑换赞助商品<br>或者耐心等待交易所上市套现<br>',

  section3_t_1: '入门级赞助',
  section3_t_2: '高级赞助',
  section3_t_3: '卓越级赞助',
  section3_t_4: '至尊级赞助',

  section3_basic_1: 'DJI 大疆Osmo Action 灵眸运动相机前后双屏防抖防水<br>双屏一体，稳定如一。前置彩屏让自拍构图更精准，从此告别盲拍，自拍更有型，时刻展示好状态。RockSteady增稳抖动算法，滤除抖动同时，还能保持相机的转向运动，带来稳定流畅的拍摄画面。',
  section3_basic_2: 'AutoCare 甲醛检测/吸收一体式魔方<br>可视化的甲醛VOC检测和吸收材料，适用于汽车甲醛测试和吸收，家庭装修甲醛测试和吸收。简单易用，安全无毒，甲醛VOC吸收后核心材料颜色发生变色现象。AutoCare已经在奥迪、福特、通用、宝马等主机车型完成测试，南京大学实验室技术提供。',
  section3_medium_1: 'DJI 大疆Osmo Action 灵眸运动相机前后双屏防抖防水<br>双屏一体，稳定如一。前置彩屏让自拍构图更精准，从此告别盲拍，自拍更有型，时刻展示好状态。RockSteady增稳抖动算法，滤除抖动同时，还能保持相机的转向运动，带来稳定流畅的拍摄画面。',
  section3_medium_2: 'AutoCare 甲醛检测/吸收一体式魔方<br>可视化的甲醛VOC检测和吸收材料，适用于汽车甲醛测试和吸收，家庭装修甲醛测试和吸收。简单易用，安全无毒，甲醛VOC吸收后核心材料颜色发生变色现象。AutoCare已经在奥迪、福特、通用、宝马等主机车型完成测试，南京大学实验室技术提供。',
  section3_premium_1: 'DJI 大疆Osmo Action <br>双屏一体，稳定如一。前置彩屏让自拍构图更精准，从此告别盲拍，自拍更有型，时刻展示好状态。RockSteady增稳抖动算法，滤除抖动同时，还能保持相机的转向运动，带来稳定流畅的拍摄画面。',
  section3_premium_2: 'AutoCare 甲醛检测/吸收一体式魔方<br>可视化的甲醛VOC检测和吸收材料，适用于汽车甲醛测试和吸收，家庭装修甲醛测试和吸收。简单易用，安全无毒，甲醛VOC吸收后核心材料颜色发生变色现象。AutoCare已经在奥迪、福特、通用、宝马等主机车型完成测试，南京大学实验室技术提供。',
  section3_superme_1: 'DJI 大疆Osmo Action 灵眸运动相机前后双屏防抖防水<br>双屏一体，稳定如一。前置彩屏让自拍构图更精准，从此告别盲拍，自拍更有型，时刻展示好状态。RockSteady增稳抖动算法，滤除抖动同时，还能保持相机的转向运动，带来稳定流畅的拍摄画面。',
  section3_superme_2: 'AutoCare 甲醛检测/吸收一体式魔方<br>可视化的甲醛VOC检测和吸收材料，适用于汽车甲醛测试和吸收，家庭装修甲醛测试和吸收。简单易用，安全无毒，甲醛VOC吸收后核心材料颜色发生变色现象。AutoCare已经在奥迪、福特、通用、宝马等主机车型完成测试，南京大学实验室技术提供。',
  
  section4_t: '积分代币分配机制&奖励分配机制',
  section4_m_p: 'Stepbook加密积分在促进运动数据化和娱乐化系统来说是极其重要的因素。这些有价值的加密积分帮助用户获得更多的现实收益，让用户更多参与运动，趣味社交当然地增强健康。加密积分将会在下一代加密区块链上运行，系统征收的部分最后将会反哺全部用户。',
  section4_m_btn: '分配法则详解',
  section4_p_1: '坚持力',
  section4_p_2: '步数',
  section4_p_3: '邀请',
  section4_p_4: '粉丝',
  section4_p_5: '游戏',
  section4_p_6: '贡献度',
  section4_p_7: '活跃度',

  section5_step: '步',
  section5_pet_t: 'stepbook提供基于区块链的加密虚拟宠物提供领养，每一个宠物都是独一无二的基因，跟真实的小猫小狗一样可以繁殖、社交、遛养，它可以带来很多虚拟玩法的可能性，并且“好血缘“的加密宠物是稀缺的，它将成为你在运动时候的最好伴侣，有时候，还可以给主人带来真实的奖励。另外，它的一个优点是，永远陪伴你。',
  section5_pet_1: '澳洲大兔',
  section5_pet_2: '微笑青蛙',
  section5_pet_3: '疯狂企鹅',

  section6_t: 'stepbook区块链加密宠物是那个平行世界的你',
  section6_p1_1: '娱乐导向',
  section6_p1_2: '游戏',
  section6_p1_3: '平台提供原生游戏，以及支持第三方游戏开发，完善的宠物成长系统，无缝链接个人运动数据。甚至，它会成为你的人工智能助手。',
  section6_p2_1: '多样性',
  section6_p2_2: '独一无二',
  section6_p2_3: '基于数10个种族，宏大的世界观设定，提供多样性扩展可能。每个加密宠物具备去中心化DNA，并且具备繁殖可能。',
  section6_p3_1: '层级发展',
  section6_p3_2: '竞争性',
  section6_p3_3: '资源永远是稀缺的，尤其是珍贵的资源。优质的数据产生优质的虚拟宠物，支配更多资源，周而复始。',
 
  section7_t: 'stepbook小程序是区块链技术驱动的首个落地项目，极其方便的使用方式，只需要链接微信运动，即可获取初级服务。更高级别的多维数据应用，则需要使用专门区块链可穿戴设备。',
  section7_1_t: '快速注册',
  section7_1_p: '无论是IOS还是安卓，只要授权你的微信到stepbook,数据流会自动计算，不浪费一滴汗水。',
  section7_2_t: '转换',
  section7_2_p: '转换动作包含安全一致性检查，这是我们为什么需要你每次都点击转换按钮，安全性是数字资产的必然要求，如果你忘记点击转换按钮，将不会得到这些资产。',
  section7_3_t: '赞助',
  section7_3_p: '在stepbook的赞助菜单里面，你可以选择你任意喜欢的商品去兑换。赞助商的商品赞助100%投入都会分配给系统，值得注意的是，有些商品是限量的，全部的权益时效取决于赞助商的框架协议。一旦兑换，恒定总量的代币就会永久性的减少相应数量。',
  section7_4_t: '关注stepbook.io',

  section8_1_t: '06.2019',
  section8_1_p: 'stepbook.io 产品发布+路演<br>手环矿机研发+首次用户大会',
  section8_2_t: '10.2019',
  section8_2_p: 'APP发布+路演<br>加密宠物发布+首次在线跑步大赛',
  section8_3_t: '03.2020',
  section8_3_p: '地图发布+十万用户<br>首个广告模型+线下跑步大赛',
  section8_4_t: '04.2020',
  section8_4_p: '第三代区块链技术集成+首个大型战略赞助商',
  section8_5_t: '09.2020',
  section8_5_p: 'stepbook团队扩张逾20人+ZB.com 交易所上市<br>Beta版赛事开发+线下地区常规联赛开始',

  account_balance: '余额',
  account_b1: '累计天数',
  account_b2: '我的邀请',
  account_b3: '坚持奖励',
  account_b4: '公共奖池奖励',

  section9_p_1: 'stepbook与您一起迎接未来，不论你是',
  section9_p_2: '赞助商',
  section9_p_3: '用户',
  section9_p_4: '员工计划，诚邀加入',
  section9_l_1: '姓名',
  section9_l_2: '邮箱',
  section9_l_3: '城市',
  section9_l_4: '留言',
  section9_l_5: '发送',
}];
